function fmt(n, digits = 3) {
  return Number(n).toFixed(digits);
}

function bambuA1Start(machine) {
  const lift = machine.penZOffset ?? 20;
  return [
    "; Generated by my-handwriting for Bambu Lab A1",
    `; ${new Date().toISOString()}`,
    `; bed 256x256  paper ${machine.paperWidth}x${machine.paperHeight}mm`,
    `; origin X${machine.originX} Y${machine.originY}  Zup ${machine.zUp} Zdown ${machine.zDown}  penZOffset ${lift}`,
    "; Homing: nozzle probes at X128 Y2 so the pen can hang off the back of the bed.",
    "; Then Z rises by penZOffset and G92 Z0 — that height is pen-on-paper.",
    "; Start penZOffset HIGH (~20mm) and lower it until the nib just marks paper.",
    "M104 S0 ; no hotend heat",
    "M140 S0 ; no bed heat",
    "M106 S0 ; part fan off",
    "M412 S0 ; filament runout off",
    "M204 S6000",
    "M630 S0 P0 ; no AMS / no filament tool",
    "G90",
    "M220 S100",
    "M221 S100",
    "M960 S5 P1 ; toolhead LED on",
    "G28 X ; home X only",
    "G91",
    "G1 Z5 F1200 ; lift before moving the bed",
    "G90",
    "G0 X128 F18000 ; center of the 256mm A1 bed",
    "G0 Y2 F3000 ; bed back — nozzle can touch, pen hangs off the rear edge",
    "G91",
    "G1 Z-5 F1200",
    "G90",
    "G28 Z P0 T300 ; nozzle home. WATCH this. Abort if the pen hits first.",
    `G1 Z${fmt(lift, 1)} F600 ; rise by pen-below-nozzle offset`,
    "G92 Z0 ; Z0 is now pen tip at paper height",
    "M211 X1 Y1 Z1 ; software endstops",
    "G90",
    `G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`,
  ];
}

function bambuA1End(machine) {
  return [
    `G0 Z${fmt(Math.max(machine.zUp, 8))} F900`,
    "G0 Z40 F900 ; cap the pen here if you want",
    "G0 X0 Y254 F18000 ; present the page at the front",
    "M106 S0",
    "M400",
    "M18 X Y Z ; motors off",
    "; end my-handwriting A1",
  ];
}

function header(machine, extra = []) {
  if (machine.flavor === "bambu_a1") {
    return [...bambuA1Start(machine), ...extra];
  }

  const lines = [
    "; Generated by my-handwriting",
    `; ${new Date().toISOString()}`,
    `; bed ${machine.bedX}x${machine.bedY}mm  paper ${machine.paperWidth}x${machine.paperHeight}mm`,
    `; origin X${machine.originX} Y${machine.originY}  Zup ${machine.zUp} Zdown ${machine.zDown}`,
    "G21 ; millimeters",
    "G90 ; absolute",
    "M82 ; absolute extrusion (unused)",
    "M104 S0 ; no hotend heat",
    "M140 S0 ; no bed heat",
  ];
  if (machine.flavor === "marlin" || machine.flavor === "klipper") {
    lines.push("; M302 P1 ; uncomment if firmware blocks motion with a cold hotend");
  }
  if (machine.homeXY) {
    lines.push("G28 X Y ; home X/Y only — do not home Z with a pen mounted");
  }
  lines.push(`G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`);
  lines.push(...extra);
  return lines;
}

function footer(machine) {
  if (machine.flavor === "bambu_a1") return bambuA1End(machine);
  return [
    `G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`,
    `G0 X0 Y${fmt(Math.max(machine.bedY - 10, 0))} F${machine.travelFeed} ; park`,
    "M84 ; steppers off",
    "; end my-handwriting",
  ];
}

export function paperToMachine(p, machine) {
  const x = machine.originX + p.x;
  const y = machine.yDownIsNegative
    ? machine.originY - p.y
    : machine.originY + p.y;
  return { x, y };
}

export function strokesToGcode(strokes, machine, { dryRun = false, title = "note" } = {}) {
  const zWrite = dryRun ? machine.zUp : machine.zDown;
  const lines = header(machine, [`; job ${title}${dryRun ? " DRY RUN (pen stays up)" : ""}`]);
  let penDown = false;
  const warnings = [];

  const inBounds = (pt) =>
    pt.x >= 0 && pt.y >= 0 && pt.x <= machine.bedX && pt.y <= machine.bedY;

  for (const stroke of strokes) {
    if (!stroke.length) continue;
    const start = paperToMachine(stroke[0], machine);
    if (!inBounds(start)) warnings.push(`travel out of bed near ${fmt(start.x)},${fmt(start.y)}`);
    if (penDown) {
      lines.push(`G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`);
      penDown = false;
    }
    lines.push(`G0 X${fmt(start.x)} Y${fmt(start.y)} F${machine.travelFeed}`);
    lines.push(`G1 Z${fmt(zWrite)} F${Math.min(machine.travelFeed, 1200)}`);
    penDown = true;
    for (let i = 1; i < stroke.length; i++) {
      const m = paperToMachine(stroke[i], machine);
      if (!inBounds(m)) warnings.push(`write out of bed near ${fmt(m.x)},${fmt(m.y)}`);
      lines.push(`G1 X${fmt(m.x)} Y${fmt(m.y)} F${machine.writeFeed}`);
    }
  }

  if (penDown) lines.push(`G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`);
  lines.push(...footer(machine));

  const uniqueWarn = [...new Set(warnings)];
  if (uniqueWarn.length) {
    lines.splice(4, 0, ...uniqueWarn.slice(0, 12).map((w) => `; WARNING: ${w}`));
  }

  return { gcode: lines.join("\n") + "\n", warnings: uniqueWarn };
}

export function calibrationSquareGcode(machine) {
  const size = 20;
  const strokes = [[
    { x: 0, y: 0 },
    { x: size, y: 0 },
    { x: size, y: size },
    { x: 0, y: size },
    { x: 0, y: 0 },
  ]];
  return strokesToGcode(strokes, machine, { title: "20mm-calibration-square" });
}
