function fmt(n, digits = 3) {
  return Number(n).toFixed(digits);
}

function bambuA1Start(machine) {
  const lift = machine.penZOffset ?? 20;
  // After nozzle-home, always park high in *machine* Z (mm above the bed) so the
  // pen clears the plate on the first move in from Y2. G92 still makes Z0 =
  // pen-on-paper. Too-small offset used to rise only a few mm, then drop to
  // Z-up (4 mm) before the bed came forward — Sharpie hits the rear edge.
  const zUp = Number(machine.zUp) || 0;
  const park = Math.max(lift + Math.max(zUp, 8), 25);
  const parkLogical = park - lift;
  return [
    "; Generated by my-handwriting for Bambu Lab A1",
    `; ${new Date().toISOString()}`,
    `; bed 256x256  paper ${machine.paperWidth}x${machine.paperHeight}mm`,
    `; origin X${machine.originX} Y${machine.originY}  Zup ${machine.zUp} Zdown ${machine.zDown}  penZOffset ${lift}  xMirror ${xMirrorEnabled(machine) ? "on" : "off"}`,
    "; Homing: nozzle probes at X128 Y2 so the pen can hang off the back of the bed.",
    `; Then Z parks at ${fmt(park, 1)} mm above the bed (clears the plate) and G92 so Z0 is pen-on-paper.`,
    "; Start penZOffset HIGH (~20mm) and lower it until the nib just marks paper.",
    "M104 S0 ; no hotend heat",
    "M140 S0 ; no bed heat",
    "M106 S0 ; part fan off",
    "M412 S0 ; filament runout off",
    "M204 S6000",
    "M630 S0 P0 ; no AMS / no filament tool",
    "G90",
    "M220 S100",
    "M221 S100",
    "M960 S5 P1 ; toolhead LED on",
    "G28 X ; home X only",
    "G91",
    "G1 Z5 F1200 ; lift before moving the bed",
    "G90",
    "G0 X128 F18000 ; center of the 256mm A1 bed",
    "G0 Y2 F3000 ; bed back — nozzle can touch, pen hangs off the rear edge",
    "G91",
    "G1 Z-5 F1200",
    "G90",
    "G28 Z P0 T300 ; nozzle home. WATCH this. Abort if the pen hits first.",
    `G0 Z${fmt(park, 1)} F600 ; park above the plate before the bed moves forward`,
    `G92 Z${fmt(parkLogical, 1)} ; Z0 is pen-on-paper (nozzle ${fmt(lift, 1)} mm above the bed)`,
    "M211 X1 Y1 Z1 ; software endstops",
    "G90",
    `; holding Z${fmt(parkLogical, 1)} (pen well above the page) until the first XY move`,
  ];
}

function bambuA1End(machine) {
  return [
    `G0 Z${fmt(Math.max(machine.zUp, 8))} F900`,
    "G0 Z40 F900 ; cap the pen here if you want",
    "G0 X0 Y254 F18000 ; present the page at the front",
    "M106 S0",
    "M400",
    "M18 X Y Z ; motors off",
    "; end my-handwriting A1",
  ];
}

function header(machine, extra = []) {
  if (machine.flavor === "bambu_a1") {
    return [...bambuA1Start(machine), ...extra];
  }

  const lines = [
    "; Generated by my-handwriting",
    `; ${new Date().toISOString()}`,
    `; bed ${machine.bedX}x${machine.bedY}mm  paper ${machine.paperWidth}x${machine.paperHeight}mm`,
    `; origin X${machine.originX} Y${machine.originY}  Zup ${machine.zUp} Zdown ${machine.zDown}`,
    "G21 ; millimeters",
    "G90 ; absolute",
    "M82 ; absolute extrusion (unused)",
    "M104 S0 ; no hotend heat",
    "M140 S0 ; no bed heat",
  ];
  if (machine.flavor === "marlin" || machine.flavor === "klipper") {
    lines.push("; M302 P1 ; uncomment if firmware blocks motion with a cold hotend");
  }
  if (machine.homeXY) {
    lines.push("G28 X Y ; home X/Y only — do not home Z with a pen mounted");
  }
  lines.push(`G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`);
  lines.push(...extra);
  return lines;
}

function footer(machine) {
  if (machine.flavor === "bambu_a1") return bambuA1End(machine);
  return [
    `G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`,
    `G0 X0 Y${fmt(Math.max(machine.bedY - 10, 0))} F${machine.travelFeed} ; park`,
    "M84 ; steppers off",
    "; end my-handwriting",
  ];
}

export function xMirrorEnabled(machine) {
  if (machine.xMirror != null) return Boolean(machine.xMirror);
  return machine.flavor === "bambu_a1" || machine.preset === "bambu_a1";
}

export function paperToMachine(p, machine) {
  const x = xMirrorEnabled(machine)
    ? machine.originX + machine.paperWidth - p.x
    : machine.originX + p.x;
  const y = machine.yDownIsNegative
    ? machine.originY - p.y
    : machine.originY + p.y;
  return { x, y };
}

export function writableMachineBounds(machine) {
  const w = Number(machine.paperWidth) || 0;
  const h = Number(machine.paperHeight) || 0;
  const corners = [
    { x: 0, y: 0 },
    { x: w, y: 0 },
    { x: 0, y: h },
    { x: w, y: h },
  ].map((p) => paperToMachine(p, machine));
  const xs = corners.map((p) => p.x);
  const ys = corners.map((p) => p.y);
  return {
    minX: Math.min(...xs),
    maxX: Math.max(...xs),
    minY: Math.min(...ys),
    maxY: Math.max(...ys),
  };
}

export function analyzeBounds(strokes, machine) {
  const paperW = Number(machine.paperWidth) || 0;
  const paperH = Number(machine.paperHeight) || 0;
  const bedX = Number(machine.bedX) || 0;
  const bedY = Number(machine.bedY) || 0;
  const slop = 0.25;
  const extra = { left: 0, right: 0, top: 0, bottom: 0 };
  let offPaper = 0;
  let offBed = 0;
  let samples = 0;
  for (const stroke of strokes || []) {
    for (const p of stroke) {
      samples += 1;
      extra.left = Math.max(extra.left, -p.x);
      extra.right = Math.max(extra.right, p.x - paperW);
      extra.top = Math.max(extra.top, -p.y);
      extra.bottom = Math.max(extra.bottom, p.y - paperH);
      if (p.x < -slop || p.y < -slop || p.x > paperW + slop || p.y > paperH + slop) offPaper += 1;
      const m = paperToMachine(p, machine);
      if (m.x < -slop || m.y < -slop || m.x > bedX + slop || m.y > bedY + slop) offBed += 1;
    }
  }
  const page = writableMachineBounds(machine);
  const pageOffBed = page.minX < -slop || page.minY < -slop
    || page.maxX > bedX + slop || page.maxY > bedY + slop;
  const paperOff = extra.left > slop || extra.right > slop || extra.top > slop || extra.bottom > slop;
  const bits = [];
  if (pageOffBed) bits.push("writable area sits off the bed — shrink paper size or move origin");
  if (extra.left > slop) bits.push(`${extra.left.toFixed(1)} mm off the left`);
  if (extra.right > slop) bits.push(`${extra.right.toFixed(1)} mm off the right`);
  if (extra.top > slop) bits.push(`${extra.top.toFixed(1)} mm off the top`);
  if (extra.bottom > slop) bits.push(`${extra.bottom.toFixed(1)} mm off the bottom`);
  if (offBed && !pageOffBed) bits.push(`${offBed} G-code points off the bed`);
  return {
    extra,
    offPaper,
    offBed,
    samples,
    paperOff,
    pageOffBed,
    page,
    ok: Boolean(samples) && !paperOff && !offBed && !pageOffBed,
    empty: samples === 0,
    summary: bits.length ? bits.join(" · ") : "On the page and on the bed",
  };
}

export function strokesToGcode(strokes, machine, { dryRun = false, title = "note" } = {}) {
  const zWrite = dryRun ? machine.zUp : machine.zDown;
  const lines = header(machine, [`; job ${title}${dryRun ? " DRY RUN (pen stays up)" : ""}`]);
  let penDown = false;
  const warnings = [];
  const report = analyzeBounds(strokes, machine);
  if (!report.ok && !report.empty) warnings.push(report.summary);

  for (const stroke of strokes) {
    if (!stroke.length) continue;
    const start = paperToMachine(stroke[0], machine);
    if (penDown) {
      lines.push(`G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`);
      penDown = false;
    }
    lines.push(`G0 X${fmt(start.x)} Y${fmt(start.y)} F${machine.travelFeed}`);
    lines.push(`G1 Z${fmt(zWrite)} F${Math.min(machine.travelFeed, 1200)}`);
    penDown = true;
    for (let i = 1; i < stroke.length; i++) {
      const m = paperToMachine(stroke[i], machine);
      lines.push(`G1 X${fmt(m.x)} Y${fmt(m.y)} F${machine.writeFeed}`);
    }
  }

  if (penDown) lines.push(`G0 Z${fmt(machine.zUp)} F${machine.travelFeed}`);
  lines.push(...footer(machine));

  const uniqueWarn = [...new Set(warnings)];
  if (uniqueWarn.length) {
    lines.splice(4, 0, ...uniqueWarn.slice(0, 12).map((w) => `; WARNING: ${w}`));
  }

  return { gcode: lines.join("\n") + "\n", warnings: uniqueWarn, report };
}

export function calibrationSquareGcode(machine) {
  const size = 20;
  const strokes = [[
    { x: 0, y: 0 },
    { x: size, y: 0 },
    { x: size, y: size },
    { x: 0, y: size },
    { x: 0, y: 0 },
  ]];
  return strokesToGcode(strokes, machine, { title: "20mm-calibration-square" });
}
